# Dockerfile.test
FROM python:3.11-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the directory to the container
COPY . .


RUN pip install -U requirements.txt

EXPOSE 80
# Set the command to run coverage on the test_math.py file
CMD ["python" , "main.py"]