# Dockerfile.test
FROM python:3.11-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the directory to the container
COPY . .


RUN pip install -r requirements.txt

EXPOSE 80

CMD ["python" , "main.py"]